apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: policy1000
  namespace: calico-test
spec:
  egress:    
    - action: Allow
  ingress:
    - action: Allow
  order: 1000
  types:
  - Egress
  - Ingress
  
