apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: policy100
spec:
  egress:    
    - action: Allow
  ingress:
    - action: Allow
  order: 100
  types:
  - Egress
  - Ingress
  
